language: android
android:
  components:
    - build-tools-23.0.2
    - android-23
    - android-L
    - sys-img-x86-android-tv-l
    - add-on
    - extra

notifications:
  email: false

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
script: ./gradlew clean build
